In [1]:
import pandas as pd
import numpy as np
from joblib import dump

In [2]:
X_train = np.load('../data/processed/X_train.npy')
X_val   = np.load('../data/processed/X_val.npy'  )
X_test  = np.load('../data/processed/X_test.npy' )
y_train = np.load('../data/processed/y_train.npy')
y_val   = np.load('../data/processed/y_val.npy'  )
y_test  = np.load('../data/processed/y_test.npy' )

In [3]:
X_train.shape

(5120, 19)

In [4]:
from sklearn.linear_model import LogisticRegression

In [8]:
y_base_med = np.full((len(y_train), 1), 1)

In [9]:
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
print("score on test: " + str(lr.score(X_test, y_test)))
print("score on train: "+ str(lr.score(X_train, y_train)))
print("score on train: "+ str(lr.score(X_train, y_base_med)))

score on test: 0.835625
score on train: 0.8390625
score on train: 0.987890625


In [83]:
dump(lr, '../models/logreg.joblib')

['../models/logreg.joblib']

In [11]:
from sklearn.metrics import roc_auc_score

In [14]:
lr.predict_proba(X_train)

array([[0.35481219, 0.64518781],
       [0.13835926, 0.86164074],
       [0.21230303, 0.78769697],
       ...,
       [0.11986243, 0.88013757],
       [0.07406753, 0.92593247],
       [0.48022053, 0.51977947]])

In [16]:
lr.predict(X_train)

[1 1 1 ... 1 1 1]


In [17]:
from collections import Counter

In [18]:
Counter(lr.predict(X_train))

Counter({1: 5058, 0: 62})

In [19]:
Counter(y_train)

Counter({1: 4286, 0: 834})

In [31]:
df_te = pd.read_csv('../data/raw/2022_test.csv')

In [41]:
df_te.shape

(3799, 20)

In [21]:
df_te_cleaned = df_te.copy()

In [23]:
df_te_cleaned.drop('Id', axis=1, inplace=True)

In [24]:
list(df_te_cleaned.columns)

['GP',
 'MIN',
 'PTS',
 'FGM',
 'FGA',
 'FG%',
 '3P Made',
 '3PA',
 '3P%',
 'FTM',
 'FTA',
 'FT%',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TOV']

In [26]:
from joblib import load

In [27]:
scaler = load('../models/scaler.joblib')

In [28]:
df_te_cleaned = scaler.transform(df_te_cleaned)

In [34]:
Counter(lr.predict(df_te_cleaned))

Counter({1: 3756, 0: 43})

In [30]:
lr.predict_proba(df_te_cleaned)

array([[0.16323   , 0.83677   ],
       [0.17965332, 0.82034668],
       [0.08190405, 0.91809595],
       ...,
       [0.26453628, 0.73546372],
       [0.03846541, 0.96153459],
       [0.23907666, 0.76092334]])

In [52]:
df_pred = pd.DataFrame(lr.predict_proba(df_te_cleaned))

In [58]:
df_pred[1].to_csv('../data/processed/test_1.csv')

## auroc
target = y_val<br>
predictions<br> 
prediction probs = <br>

In [75]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

In [63]:
target = np.array(y_test)

In [76]:
df_pred_1 = pd.DataFrame(lr.predict_proba(X_test))
df_pred_2 = pd.DataFrame(lr.predict(X_test))

In [78]:
pred_probs = np.array(df_pred_1[1])
pred_actual = np.array(df_pred_2)

In [80]:
roc_auc_score(target, pred_probs)

0.7096980741762302

In [81]:
accuracy_score(target, pred_actual)

0.835625

In [67]:
y_mean = y_train.mean()
y_mean

0.837109375

In [72]:
y_base = np.full((len(y_test), 1), y_mean)
y_base

array([[0.83710938],
       [0.83710938],
       [0.83710938],
       ...,
       [0.83710938],
       [0.83710938],
       [0.83710938]])

In [69]:
roc_auc_score(target, y_base)

0.5

In [70]:
y_base_1 = np.full((len(y_test), 1), 1)

In [71]:
roc_auc_score(target, y_base_1)

0.5

In [82]:
accuracy_score(target, y_base_1)

0.839375

In [73]:
y_base_05 = np.full((len(y_test), 1), 0.5)

In [74]:
roc_auc_score(target, y_base_05)

0.5