In [16]:
import pandas as pd
import numpy as np
from joblib import dump

from sklearn.linear_model import LogisticRegression

from collections import Counter

In [37]:
# load processed upscaled datasets


X_ups_data = np.load('../data/processed/X_ups_data.npy')
X_ups_test = np.load('../data/processed/X_ups_test.npy')
y_ups_data = np.load('../data/processed/y_ups_data.npy')
y_ups_test = np.load('../data/processed/y_ups_test.npy')

# X_train = np.load('../data/processed/X_train.npy')
# X_val   = np.load('../data/processed/X_val.npy'  )
X_test  = np.load('../data/processed/X_test.npy' )
# y_train = np.load('../data/processed/y_train.npy')
# y_val   = np.load('../data/processed/y_val.npy'  )
y_test  = np.load('../data/processed/y_test.npy' )


In [47]:
print(X_ups_data.shape)
print(X_ups_test.shape)
print(y_ups_data.shape)
print(y_ups_test.shape)

print(X_test.shape)
print(y_test.shape)
print(Counter(y_test))

(10670, 19)
(2668, 19)
(10670,)
(2668,)
(1600, 19)
(1600,)
Counter({1: 1343, 0: 257})


In [13]:
lr=LogisticRegression(max_iter=1000)
lr.fit(X_ups_data, y_ups_data)


LogisticRegression(max_iter=1000)

In [83]:
dump(lr, '../models/logreg.joblib')

['../models/logreg.joblib']

In [11]:
from sklearn.metrics import roc_auc_score

In [14]:
lr.predict_proba(X_ups_data)

array([[0.6512953 , 0.3487047 ],
       [0.80146224, 0.19853776],
       [0.2706868 , 0.7293132 ],
       ...,
       [0.17627586, 0.82372414],
       [0.84935344, 0.15064656],
       [0.23228377, 0.76771623]])

In [15]:
lr.predict(X_ups_data)

array([0, 0, 1, ..., 1, 0, 1])

In [17]:
Counter(lr.predict(X_ups_data))

Counter({0: 5487, 1: 5183})

In [18]:
Counter(y_ups_data)

Counter({0: 5337, 1: 5333})

In [19]:
df_te = pd.read_csv('../data/raw/2022_test.csv')

In [41]:
df_te.shape

(3799, 20)

In [20]:
df_te_cleaned = df_te.copy()

In [21]:
df_te_cleaned.drop('Id', axis=1, inplace=True)

In [22]:
list(df_te_cleaned.columns)

['GP',
 'MIN',
 'PTS',
 'FGM',
 'FGA',
 'FG%',
 '3P Made',
 '3PA',
 '3P%',
 'FTM',
 'FTA',
 'FT%',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TOV']

In [23]:
from joblib import load

In [24]:
scaler = load('../models/scaler_ups.joblib')

In [25]:
df_te_cleaned = scaler.transform(df_te_cleaned)

In [26]:
Counter(lr.predict(df_te_cleaned))

Counter({1: 2225, 0: 1574})

In [30]:
lr.predict_proba(df_te_cleaned)

array([[0.16323   , 0.83677   ],
       [0.17965332, 0.82034668],
       [0.08190405, 0.91809595],
       ...,
       [0.26453628, 0.73546372],
       [0.03846541, 0.96153459],
       [0.23907666, 0.76092334]])

In [27]:
df_pred = pd.DataFrame(lr.predict_proba(df_te_cleaned))

In [28]:
df_pred[1].to_csv('../data/processed/test_ups.csv')

## auroc
target = y_val<br>
predictions<br> 
prediction probs = <br>

In [31]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

In [39]:
target = np.array(y_test)

In [40]:
df_pred_1 = pd.DataFrame(lr.predict_proba(X_test))
df_pred_2 = pd.DataFrame(lr.predict(X_test))

In [41]:
pred_probs = np.array(df_pred_1[1])
pred_actual = np.array(df_pred_2)

In [42]:
roc_auc_score(target, pred_probs)

0.7120564622440613

In [43]:
accuracy_score(target, pred_actual)

0.5725

In [67]:
y_mean = y_train.mean()
y_mean

0.837109375

In [72]:
y_base = np.full((len(y_test), 1), y_mean)
y_base

array([[0.83710938],
       [0.83710938],
       [0.83710938],
       ...,
       [0.83710938],
       [0.83710938],
       [0.83710938]])

In [69]:
roc_auc_score(target, y_base)

0.5

In [70]:
y_base_1 = np.full((len(y_test), 1), 1)

In [71]:
roc_auc_score(target, y_base_1)

0.5

In [82]:
accuracy_score(target, y_base_1)

0.839375

In [73]:
y_base_05 = np.full((len(y_test), 1), 0.5)

In [74]:
roc_auc_score(target, y_base_05)

0.5